const mockProducts = [
  { id: 1, name: 'Wireless Bluetooth Headphones', price: 2499, originalPrice: 3999, rating: 4.3, reviewCount: 1284, image: '🎧', inStock: true, category: 'electronics', brand: 'SoundCore', description: 'Immerse yourself in rich, high-fidelity sound with these over-ear wireless headphones. Featuring active noise cancellation, 30-hour battery life, and a comfortable memory-foam headband for all-day wear.' },
  { id: 2, name: 'Smart Fitness Watch', price: 3299, originalPrice: 4999, rating: 4.1, reviewCount: 856, image: '⌚', inStock: true, category: 'electronics', brand: 'FitPulse', description: 'Track your heart rate, sleep, and workouts with precision. Water-resistant up to 50m, with a 7-day battery life and real-time notifications synced to your phone.' },
  { id: 3, name: 'Portable Bluetooth Speaker', price: 1799, originalPrice: 2499, rating: 4.5, reviewCount: 2103, image: '🔊', inStock: true, category: 'electronics', brand: 'SoundCore', description: 'Compact yet powerful, this speaker delivers 360° sound with deep bass. IPX7 waterproof rating makes it perfect for outdoor adventures and pool parties.' },
  { id: 4, name: 'Mechanical Gaming Keyboard', price: 4499, originalPrice: 5999, rating: 4.6, reviewCount: 634, image: '⌨️', inStock: false, category: 'electronics', brand: 'KeyTech', description: 'RGB backlit mechanical keyboard with hot-swappable switches, aircraft-grade aluminum frame, and dedicated media controls for the ultimate gaming setup.' },
  { id: 5, name: 'USB-C Fast Charger', price: 899, originalPrice: 1299, rating: 4.0, reviewCount: 421, image: '🔌', inStock: true, category: 'electronics', brand: 'PowerMax', description: '65W GaN fast charger that charges your laptop and phone simultaneously. Compact design fits easily into any travel bag.' },
  { id: 6, name: 'Wireless Mouse', price: 699, originalPrice: 999, rating: 4.2, reviewCount: 967, image: '🖱️', inStock: true, category: 'electronics', brand: 'KeyTech', description: 'Ergonomic wireless mouse with adjustable DPI, silent clicks, and a 12-month battery life on a single AA battery.' },
  { id: 7, name: 'Running Shoes', price: 2199, originalPrice: 3499, rating: 4.4, reviewCount: 1502, image: '👟', inStock: true, category: 'fashion', brand: 'StrideFit', description: 'Lightweight running shoes with responsive cushioning and breathable mesh upper, engineered for long-distance comfort.' },
  { id: 8, name: 'Denim Jacket', price: 1899, originalPrice: 2799, rating: 4.0, reviewCount: 312, image: '🧥', inStock: true, category: 'fashion', brand: 'UrbanWear', description: 'Classic fit denim jacket made from premium washed cotton, a timeless layer for any casual outfit.' },
  { id: 9, name: 'Leather Handbag', price: 2999, originalPrice: 4499, rating: 4.3, reviewCount: 578, image: '👜', inStock: true, category: 'fashion', brand: 'UrbanWear', description: 'Genuine leather handbag with multiple compartments, adjustable strap, and a timeless silhouette that pairs with any outfit.' },
  { id: 10, name: 'Non-Stick Cookware Set', price: 3499, originalPrice: 4999, rating: 4.5, reviewCount: 890, image: '🍳', inStock: true, category: 'home-kitchen', brand: 'HomeEase', description: '10-piece non-stick cookware set with heat-resistant handles, dishwasher safe, and compatible with all stovetops including induction.' },
  { id: 11, name: 'LED Desk Lamp', price: 799, originalPrice: 1199, rating: 4.1, reviewCount: 445, image: '💡', inStock: true, category: 'home-kitchen', brand: 'HomeEase', description: 'Adjustable LED desk lamp with 5 brightness levels and 3 color modes, plus a built-in USB charging port.' },
  { id: 12, name: 'Yoga Mat', price: 599, originalPrice: 899, rating: 4.6, reviewCount: 1203, image: '🧘', inStock: true, category: 'sports', brand: 'StrideFit', description: 'Extra-thick 6mm yoga mat with non-slip texture on both sides, lightweight and easy to carry with the included strap.' },
]

export default mockProducts