const mockProducts = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    price: 2499,
    originalPrice: 3999,
    rating: 4.3,
    reviewCount: 1284,
    image: '🎧',
    inStock: true,
  },
  {
    id: 2,
    name: 'Smart Fitness Watch',
    price: 3299,
    originalPrice: 4999,
    rating: 4.1,
    reviewCount: 856,
    image: '⌚',
    inStock: true,
  },
  {
    id: 3,
    name: 'Portable Bluetooth Speaker',
    price: 1799,
    originalPrice: 2499,
    rating: 4.5,
    reviewCount: 2103,
    image: '🔊',
    inStock: true,
  },
  {
    id: 4,
    name: 'Mechanical Gaming Keyboard',
    price: 4499,
    originalPrice: 5999,
    rating: 4.6,
    reviewCount: 634,
    image: '⌨️',
    inStock: false,
  },
  {
    id: 5,
    name: 'USB-C Fast Charger',
    price: 899,
    originalPrice: 1299,
    rating: 4.0,
    reviewCount: 421,
    image: '🔌',
    inStock: true,
  },
  {
    id: 6,
    name: 'Wireless Mouse',
    price: 699,
    originalPrice: 999,
    rating: 4.2,
    reviewCount: 967,
    image: '🖱️',
    inStock: true,
  },
]

export default mockProducts